#!/bin/bash
# define an array called cararray
# using c- style syntax
cars=("Ford" "Jaguar" "Geely" "Daf" "BMw" "Kia" "Opel" )
len=${#cars[*]} # get total elements in an array

#print it
for (( i=0; i<${len}; i++));

do
	echo "${cars[$i]}"
done
